export const coursesData = [
  {
    courseId: 1,
    title: "JavaScript Fundamentals",
    description: "Learn the basics of JavaScript programming language",
    instructorName: "John Doe",
    courseImageUrl: "https://example.com/js-course.jpg",
    difficulty: "Beginner",
    durationHours: 20,
    likesCount: 45,
    commentsCount: 12,
    enrolledCount: 150,
    isPublished: true,
    createdBy: 1,
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16")
  },
  {
    courseId: 2,
    title: "Data Structures and Algorithms",
    description: "Master fundamental data structures and algorithms",
    instructorName: "Alice Smith",
    courseImageUrl: "https://example.com/dsa-course.jpg",
    difficulty: "Intermediate",
    durationHours: 40,
    likesCount: 78,
    commentsCount: 23,
    enrolledCount: 89,
    isPublished: true,
    createdBy: 2,
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21")
  },
  {
    courseId: 3,
    title: "React Development",
    description: "Build modern web applications with React",
    instructorName: "Bob Wilson",
    courseImageUrl: "https://example.com/react-course.jpg",
    difficulty: "Intermediate",
    durationHours: 30,
    likesCount: 62,
    commentsCount: 18,
    enrolledCount: 124,
    isPublished: true,
    createdBy: 3,
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26")
  },
  {
    courseId: 4,
    title: "Python for Data Science",
    description: "Learn Python programming for data analysis and machine learning",
    instructorName: "Alice Smith",
    courseImageUrl: "https://example.com/python-ds-course.jpg",
    difficulty: "Beginner",
    durationHours: 35,
    likesCount: 91,
    commentsCount: 31,
    enrolledCount: 203,
    isPublished: true,
    createdBy: 2,
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28")
  }
];
