export const problemsData = [
  {
    problemId: 1,
    title: "Two Sum",
    description: "Given an array of integers and a target sum, return indices of two numbers that add up to the target.",
    difficulty: "Easy",
    problemType: "Array",
    tags: JSON.stringify(["Array", "Hash Table", "Two Pointers"]),
    sampleInput: "[2,7,11,15], target = 9",
    sampleOutput: "[0,1]",
    constraints: "2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9\n-10^9 <= target <= 10^9",
    hints: "Use a hash map to store complement values",
    timeLimit: 1,
    memoryLimit: 256,
    likesCount: 234,
    commentsCount: 45,
    submissionsCount: 1250,
    acceptedCount: 890,
    acceptanceRate: 71.2,
    isPublished: true,
    createdBy: 1,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17")
  },
  {
    problemId: 2,
    title: "Valid Parentheses",
    description: "Given a string containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
    difficulty: "Easy",
    problemType: "Stack",
    tags: JSON.stringify(["String", "Stack"]),
    sampleInput: "\"()[]{}\"",
    sampleOutput: "true",
    constraints: "1 <= s.length <= 10^4\ns consists of parentheses only '()[]{}'",
    hints: "Use a stack to keep track of opening brackets",
    timeLimit: 1,
    memoryLimit: 256,
    likesCount: 189,
    commentsCount: 32,
    submissionsCount: 987,
    acceptedCount: 743,
    acceptanceRate: 75.3,
    isPublished: true,
    createdBy: 2,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18")
  },
  {
    problemId: 3,
    title: "Binary Tree Inorder Traversal",
    description: "Given the root of a binary tree, return the inorder traversal of its nodes' values.",
    difficulty: "Medium",
    problemType: "Tree",
    tags: JSON.stringify(["Tree", "Binary Tree", "Depth-First Search"]),
    sampleInput: "root = [1,null,2,3]",
    sampleOutput: "[1,3,2]",
    constraints: "The number of nodes in the tree is in the range [0, 100]\n-100 <= Node.val <= 100",
    hints: "Use recursion or iterative approach with stack",
    timeLimit: 2,
    memoryLimit: 256,
    likesCount: 156,
    commentsCount: 28,
    submissionsCount: 678,
    acceptedCount: 445,
    acceptanceRate: 65.6,
    isPublished: true,
    createdBy: 1,
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19")
  },
  {
    problemId: 4,
    title: "Maximum Subarray",
    description: "Given an integer array nums, find the contiguous subarray with the largest sum, and return its sum.",
    difficulty: "Medium",
    problemType: "Dynamic Programming",
    tags: JSON.stringify(["Array", "Dynamic Programming", "Divide and Conquer"]),
    sampleInput: "[-2,1,-3,4,-1,2,1,-5,4]",
    sampleOutput: "6",
    constraints: "1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4",
    hints: "Use Kadane's algorithm for optimal solution",
    timeLimit: 2,
    memoryLimit: 256,
    likesCount: 298,
    commentsCount: 67,
    submissionsCount: 1456,
    acceptedCount: 892,
    acceptanceRate: 61.3,
    isPublished: true,
    createdBy: 2,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20")
  }
];