export const usersData = [
  {
    userId: 1,
    username: "john_doe",
    email: "john@example.com",
    firstName: "John",
    lastName: "Doe",
    designation: "Software Engineer",
    place: "San Francisco, CA",
    skills: JSON.stringify(["JavaScript", "TypeScript", "React", "Node.js"]),
    bio: "Full-stack developer with 5 years of experience",
    avatarUrl: "https://example.com/avatar1.jpg",
    totalProblemsSolved: 25,
    easyProblemsSolved: 10,
    mediumProblemsSolved: 12,
    hardProblemsSolved: 3,
    currentStreak: 7,
    longestStreak: 15,
    ranking: 1,
    points: 1250,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15")
  },
  {
    userId: 2,
    username: "alice_smith",
    email: "alice@example.com",
    firstName: "Alice",
    lastName: "Smith",
    designation: "Data Scientist",
    place: "New York, NY",
    skills: JSON.stringify(["Python", "Machine Learning", "SQL", "R"]),
    bio: "Data scientist passionate about AI and analytics",
    avatarUrl: "https://example.com/avatar2.jpg",
    totalProblemsSolved: 18,
    easyProblemsSolved: 8,
    mediumProblemsSolved: 7,
    hardProblemsSolved: 3,
    currentStreak: 3,
    longestStreak: 10,
    ranking: 2,
    points: 890,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20")
  },
  {
    userId: 3,
    username: "bob_wilson",
    email: "bob@example.com",
    firstName: "Bob",
    lastName: "Wilson",
    designation: "Frontend Developer",
    place: "Austin, TX",
    skills: JSON.stringify(["HTML", "CSS", "JavaScript", "Vue.js"]),
    bio: "Frontend developer specializing in modern web technologies",
    avatarUrl: "https://example.com/avatar3.jpg",
    totalProblemsSolved: 12,
    easyProblemsSolved: 6,
    mediumProblemsSolved: 4,
    hardProblemsSolved: 2,
    currentStreak: 5,
    longestStreak: 8,
    ranking: 3,
    points: 640,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25")
  },
  {
    userId: 4,
    username: "sarah_johnson",
    email: "sarah@example.com",
    firstName: "Sarah",
    lastName: "Johnson",
    designation: "DevOps Engineer",
    place: "Seattle, WA",
    skills: JSON.stringify(["Docker", "Kubernetes", "AWS", "Python"]),
    bio: "DevOps engineer with expertise in cloud infrastructure",
    avatarUrl: "https://example.com/avatar4.jpg",
    totalProblemsSolved: 8,
    easyProblemsSolved: 4,
    mediumProblemsSolved: 3,
    hardProblemsSolved: 1,
    currentStreak: 2,
    longestStreak: 6,
    ranking: 4,
    points: 420,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01")
  },
  {
    userId: 5,
    username: "mike_admin",
    email: "admin@example.com",
    firstName: "Mike",
    lastName: "Admin",
    designation: "Platform Administrator",
    place: "Remote",
    skills: JSON.stringify(["System Administration", "Security", "Monitoring"]),
    bio: "Platform administrator ensuring smooth operations",
    avatarUrl: "https://example.com/avatar5.jpg",
    totalProblemsSolved: 0,
    easyProblemsSolved: 0,
    mediumProblemsSolved: 0,
    hardProblemsSolved: 0,
    currentStreak: 0,
    longestStreak: 0,
    ranking: null,
    points: 0,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10")
  }
];
